from pygments.style import Style
from pygments.token import Keyword, Name, Comment, String, Error, \
    Number, Operator, Generic, Token, Punctuation


class MonokaiLightStyle(Style):
    styles = {
        Token: '#2f2f2f',
        Comment: '#757575',
        Comment.Preproc: '#ae81ff',
        Keyword: '#f92672',
        Keyword.Type: '#66d9ef',
        Operator: '#f92672',
        Punctuation: '#2f2f0f',
        Name: '#2f2f2f',
        Name.Function: '#a6e22e',
        Name.Class: '#a6e22e',
        Name.Decorator: '#ae81ff',
        Name.Namespace: '#ae81ff',
        Name.Exception: '#f92672',
        Name.Variable: '#2f2f2f',
        Name.Constant: '#ae81ff',
        Name.Attribute: '#a6e22e',
        Name.Tag: '#f92672',
        String: '#e6db74',
        String.Char: '#e6db74',
        String.Doc: '#757575',
        String.Double: '#e6db74',
        String.Escape: '#ae81ff',
        String.Interpol: '#f92672',
        String.Other: '#e6db74',
        String.Regex: '#e6db74',
        String.Single: '#e6db74',
        String.Symbol: '#e6db74',
        Number: '#ae81ff',
        Number.Float: '#ae81ff',
        Number.Hex: '#ae81ff',
        Number.Integer: '#ae81ff',
        Number.Oct: '#ae81ff',
        Generic: '#2f2f2f',
        Generic.Deleted: '#f92672',
        Generic.Emph: '#2f2f2f',
        Generic.Error: '#f92672',
        Generic.Heading: '#2f2f2f',
        Generic.Inserted: '#a6e22e',
        Generic.Output: '#757575',
        Generic.Prompt: '#2f2f2f',
        Generic.Strong: '#2f2f2f',
        Generic.Subheading: '#2f2f2f',
        Generic.Traceback: '#f92672',
        Error: '#f92672',
    }