from pygments.style import Style
from pygments.token import Token, Comment, Name, Keyword, Number, Operator, Punctuation, Generic


class CustomHTMLStyleDark(Style):
    background_color = "#1e1e1e"
    styles = {
        Token: '#d4d4d4',
        Token.Tag: '#569cd6',
        Token.Tag.Name: '#4ec9b0',
        Token.Tag.Punctuation: '#808080',
        Token.Tag.Attribute: '#9cdcfe',
        Token.Tag.Attribute.Name: '#9cdcfe',
        Token.Tag.Attribute.Value: '#ce9178',
        Token.String: '#ce9178',
        Token.String.Single: '#ce9178',
        Token.String.Double: '#ce9178',
        Token.String.Symbol: '#569cd6',
        Token.String.Interpol: '#d7ba7d',
        Comment: '#6a9955',
        Comment.Single: '#6a9955',
        Comment.Multiline: '#6a9955',
        Comment.Preproc: '#4ec9b0',
        Comment.Special: '#569cd6',
        Keyword: '#c586c0',
        Keyword.Constant: '#569cd6',
        Keyword.Declaration: '#4ec9b0',
        Keyword.Namespace: '#c586c0',
        Keyword.Pseudo: '#d7ba7d',
        Keyword.Reserved: '#c586c0',
        Keyword.Type: '#4ec9b0',
        Operator: '#d4d4d4',
        Operator.Word: '#c586c0',
        Number: '#b5cea8',
        Number.Float: '#b5cea8',
        Number.Integer: '#b5cea8',
        Number.Hex: '#d7ba7d',
        Number.Oct: '#d7ba7d',
        Number.Bin: '#d7ba7d',
        Name: '#d4d4d4',
        Name.Attribute: '#9cdcfe',
        Name.Builtin: '#4ec9b0',
        Name.Builtin.Pseudo: '#569cd6',
        Name.Class: '#4ec9b0',
        Name.Constant: '#d7ba7d',
        Name.Decorator: '#c586c0',
        Name.Entity: '#b5cea8',
        Name.Exception: '#569cd6',
        Name.Function: '#dcdcaa',
        Name.Function.Magic: '#c586c0',
        Name.Label: '#4ec9b0',
        Name.Namespace: '#c586c0',
        Name.Other: '#d4d4d4',
        Name.Property: '#d7ba7d',
        Name.Tag: '#569cd6',
        Name.Variable: '#d4d4d4',
        Name.Variable.Class: '#4ec9b0',
        Name.Variable.Global: '#569cd6',
        Name.Variable.Instance: '#dcdcaa',
        Name.Variable.Magic: '#c586c0',
        Punctuation: '#d4d4d4',
        Punctuation.Marker: '#569cd6',
        Generic: '#d4d4d4',
        Generic.Deleted: '#f44747',
        Generic.Emph: '#c586c0 italic',
        Generic.Error: '#f44747 bold',
        Generic.Heading: '#4ec9b0 bold',
        Generic.Inserted: '#b5cea8',
        Generic.Output: '#808080',
        Generic.Prompt: '#4ec9b0 bold',
        Generic.Strong: '#d4d4d4 bold',
        Generic.Subheading: '#c586c0 bold',
        Generic.Traceback: '#f44747',
        Token.Doctype: '#6a9955 italic',
        Token.Entity: '#d7ba7d bold',
        Token.Meta: '#9cdcfe',
        Token.Meta.Keyword: '#c586c0',
        Token.Meta.Tag: '#569cd6',
    }
